# Site settings
email: sriharsha.sheshn@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Thoughts penned
description: 
url: ""
twitter_username: sriharshasheshn
default_img: https://unsplash.it/2000/1200?image=1058

# Profile settings
name: Sriharsha Sheshanarayana
profile_img: https://unsplash.it/2000/1200?image=447
profile: Thomas Vaeth was born in New York, raised in Pennsylvania, and transplanted in Washington. He was a biochemist, but now he's a web developer at Urban Influence. He's also semi-decent at table tennis.
social:
  github: https://github.com/rashhairs
  #codepen: http://codepen.io/thomasvaeth/
  #linkedin: https://www.linkedin.com/in/thomasvaeth
  twitter: https://twitter.com/sriharshasheshn
  #facebook: https://www.facebook.com/thomas.vaeth
  instagram: https://www.instagram.com/rashhairs/

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
